### ISSUE TITLE
Lời giải bài tập chưa kĩ lưỡng

### ISSUE THREAD

**Issue by mtphung711** [edtechkidsvn/c4ejs-student-book#11]
File: Biến

Line 62 (Đáp án bài tập cuối cùng mục II)

Description: Mục đích của bài tập là gây bối rối cho học sinh khi câu lệnh console.log(x) không nằm trong scope của let x = 20 (2 dấu ngoặc nhọn ở trong) mà chỉ nằm trong scope của let y = 30 (2 dấu ngoặc nhọn bao ngoài). Khi đưa ra lời giải cần nói rõ điểm này: câu lệnh console.log(x) sẽ báo lỗi nhưng câu lệnh console.log(y) sẽ cho ra kết quả là 30. 

Suggestion: Bổ sung giải thích như trên, có thể đưa ra ví dụ câu lệnh phải được viết như thế nào để in ra được biến x (nằm trong scope của x)

**Comment by edtechkidsvn** [comment]
Đã sửa lại bài tập cho dễ hình dung và giải thích kỹ hơn
