### ISSUE TITLE
Liên hệ khái niệm Declaring và Evaluating variables với những ví dụ đã thấy ở phần trước

### ISSUE THREAD

**Issue by mtphung711** [edtechkidsvn/c4ejs-student-book#12]
File: Biến

Line 63-67 (Phần 1 mục III) 

Description: Ở phần trên, học sinh đã học về Declaring variables (let x = 5) và Evaluation variables (let x). Nên nhắc lại những ví dụ này để học sinh không cảm thấy họ đang gặp phải một khái niệm hoàn toàn mới.

**Comment by edtechkidsvn** [comment]
Đã fix
