### ISSUE TITLE
Sử dụng let thay vì var làm ví dụ

### ISSUE THREAD

**Issue by mtphung711** [edtechkidsvn/c4ejs-student-book#13]
File: Biến

Line: 68-74 (Phần 2 mục III) 

Description: Chương này được thông báo là chỉ cover câu lệnh let, tuy nhiên ví dụ lại sử dụng câu lệnh var. Học viên sẽ thắc mắc ý nghĩa của câu lệnh var này.

Suggestion: Đổi ví dụ thành câu lệnh let, hoặc bổ sung giải thích ngắn gọn về câu lệnh var và const ở phần trên.

**Comment by edtechkidsvn** [comment]
Đã sửa
