### ISSUE TITLE
Ví dụ Hoisting thiếu phần thực thi lệnh

### ISSUE THREAD

**Issue by mtphung711** [edtechkidsvn/c4ejs-student-book#14]
File: Biến

Line: 68-74 (Phần 2 mục III) 

Description: Mục tiêu của phần này là chỉ ra 2 đoạn code 1 và 2 khi thực thi đều cho kết quả như nhau là x = 5. Tuy nhiên, ví dụ lại không có phần thực thi lệnh và kết quả, học sinh sẽ thấy khó hình dung.

Suggestion: Viết lại Theo trình tự sau:
1. Giải thích ngắn gọn: Hoisting là khi trong 1 số trường hợp, JS tự động thay đổi code trước khi thực thi
2. Đưa ra code 2 trước + giải thích ý nghĩa từng dòng + kết quả sau khi thực thi. 
3. Đưa ra code 1, phân tích sự bất thường khi câu lệnh in console.log(x) được đưa ra khi biến x chưa được khai báo. Sau đó chạy code, cho học sinh thấy kết quả vẫn y như Code 2
4. Kết luận về khái niệm hoisting.

**Comment by edtechkidsvn** [comment]
Lỗi này là đúng, tuy nhiên phần hoisting này không thực sự mang lại value cho người học đồng thời còn  có phần khuyến khích thói quen code không tốt về khai báo biến của học viên, đã giải quyết bằng cách bỏ cả phần hoisting này đi.
