### ISSUE TITLE
Guideline thiếu dấu chấm phẩy ";" 

### ISSUE THREAD

**Issue by mtphung711** [edtechkidsvn/c4ejs-student-book#3]
File: Giới thiệu khoá học

Line 32-33 (Mục III, bullet point 9)

Description: Học viên rất có thể quên dấu chấm phẩy, vì guideline không có dấu chấm phẩy (chỉ có trên ảnh, không có trên text).

Suggestion: Bổ sung bullet point số 10: Sau khi chạy code, nếu bạn không thấy dòng chữ Hello world hiện lên trên trình duyệt, có thể bạn đã quên dấu “;” ở cuối câu. Dấu “;” là một phần quan trọng của cú pháp JS.

**Comment by AnhQuann** [comment]
Không có dấu chấm phẩy thì code vẫn chạy được ạ. Nhưng nên có. Em đã thêm bullet point số 10 như sau:

-   Dấu chấm phẩy ( ; ) không có ý nghĩa trong việc chạy code JavaScript, bạn có thể có hoặc không, code vẫn chạy bình thường. Tuy nhiên khi file code của bạn lớn dần lên thì dấu chấm phẩy là rất cần thiết, góp phần giúp cho code trở nên sáng sủa hơn rất nhiều.
