### ISSUE TITLE
Bài tập không có lời giải

### ISSUE THREAD

**Issue by mtphung711** [edtechkidsvn/c4ejs-student-book#5]
File: Giới thiệu khoá học

Line 42-44 (Bài tập)

Description: Không có lời giải cho bài tập. Học sinh có thể thắc mắc kết quả hiện lên thế nào là đúng, có phải xuống dòng không, xuống dòng thế nào? Có phải tạo nhiều dòng console.log khi xuống dòng không?

Suggestion: Bổ sung lời giải và gợi ý cách xuống dòng (có thể làm riêng 1 mục lời giải ở cuối sách)

**Comment by edtechkidsvn** [comment]
Đã thêm lời giải
