### ISSUE TITLE
Định nghĩa biến chưa rõ ràng

### ISSUE THREAD

**Issue by mtphung711** [edtechkidsvn/c4ejs-student-book#6]
File: Biến (Variable)

Line 2-9 (Phần 1 mục I)

Description: 
1. Việc định nghĩa biến (variable) - tips trong tương quan với hằng (constant) - 100k là tốt, tuy nhiên cũng có thể gây rối cho học sinh. Trong trường hợp không tồn tại hằng số thì biến trông như thế nào, hay bắt buộc phải có hằng số thì biến số mới tồn tại? 
2. Việc kết luận vì sao tips lại là biến (variable) chưa được giải thích rõ ràng ở line 9. 

Suggestion: Viết kết luận rõ ràng hơn ở line 9. Ví dụ: _Trong ví dụ trên, tips được gọi là biến, vì nó không có giá trị cố định; giá trị của nó thay đổi theo những yếu tố khác. Trái lại, số tiền 100k được gọi là hằng số vì giá trị của nó không thay đổi. Một số ví dụ khác về biến số trong thực tế: thái độ của người yêu bạn ngày hôm nay (phụ thuộc vào độ quan tâm của bạn cho người ta trong vài ngày vừa rồi), hay số lượng hoa đào nở Tết này (phụ thuộc vào thời tiết ấm hay lạnh)._
Nhìn chung, cố gắng viết những câu kết luận rõ ràng.

**Comment by edtechkidsvn** [comment]
Đã fix
