### ISSUE TITLE
Thiếu liên kết giữa ví dụ ở Mục 1 tới khái niệm về biến

### ISSUE THREAD

**Issue by mtphung711** [edtechkidsvn/c4ejs-student-book#8]
File: Biến (Variable)

Line 10-13 (Phần 2 mục I)

Description: Ở phần 1, học sinh được biết biến là nhân tố khó chiều, hay thay đổi. Vậy có liên quan gì đến việc biến là cái hộp, mỗi lúc chỉ lưu trữ một value?

Suggestion: Bổ sung vào bullet point 1: “Giá trị (value) nằm trong hộp không cố định mà có thể thay đổi tuỳ theo những yếu tố khác hoặc theo sự sắp đặt của bạn. Hôm nay trong hộp chứa giá trị a, ngày mai có thể chứa giá trị b, cũng giống như tiền tips của Đức lúc 8h-9h là 200k, nhưng lúc 9h-10 lại chỉ có 10k vậy.”

Nhìn chung, luôn có những câu “cầu nối” để người học dễ liên tưởng từ ví dụ đến khái niệm.

**Comment by edtechkidsvn** [comment]
Đã fix như yêu cầu
