### ISSUE TITLE
Refer giữa các phần với nhau

### ISSUE THREAD

**Issue by mtphung711** [edtechkidsvn/c4ejs-student-book#9]
File: Biến

Line 18-19 (Phần 3 mục I, bullet point 3.1) 

Description: Khi đọc đến đây, học viên sẽ tự hỏi vì sao phải đặt tên biến có nghĩa, quy tắc đặt tên là gì. 

Suggestion: Nếu mình cover nó ở mục 4 thì hãy ghi rõ là sẽ đề cập ở mục 4 để học sinh không mất thời gian liên tưởng (giống như bullet point 3.3 đã làm rất tốt khi refer đến phần II!)

**Comment by edtechkidsvn** [comment]
Đã fix
